server:
  port: 8081

spring:
  profiles:
    active: local # 구동 프로필
  mvc:
    throw-exception-if-no-handler-found: true # 경로에 해당하는 라우터가 없을 때 오류를 리턴할지? - true
    static-path-pattern: /static
    hidden-method:
      filter:
        enabled: true