spring:
  application:
    name: demo
  profiles:
    active: local
  mvc:
    static-path-pattern: /static
    hidden-method:
      filter:
        enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null